name: Node.js Package

on:
  push:
    branches:
      - develop
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: mymindstorm/setup-emsdk@v6
        with:
          version: 1.39.19
          actions-cache-folder: "emsdk-cache"
      - id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: CMakeFiles Cache
        uses: actions/cache@v2
        with:
          path: CMakeFiles
          key: ${{ runner.os }}-cmakefiles-${ { hashFiles('**/CMakeLists.txt') }}-${ { hashFiles('**/CMakeCache.txt') }}-${ { hashFiles('**/CMakeFiles') } }
          restore-keys: |
            ${{ runner.os }}-cmakefiles-
      - run: npm install
      - run: npm run build
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all .
          git commit -m "Auto update pre-built results" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
